spring:
  output:
    ansi:
      enabled: always
  jpa:
    open-in-view: false
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB
      # 파일 임계값 설정
      file-size-threshold: 10KB
      enabled: true