spring:
  datasource:
    url: jdbc:mysql://pictz-db.cvwi8scws1tn.ap-northeast-2.rds.amazonaws.com/pictz?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
  sql:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google

# 랜덤 닉네임 API URL
nickname:
  api:
    url: https://www.rivestsoft.com/nickname/getRandomNickname.ajax

# image url
storage:
  local:
    path: ./uploads
    base-url: https://yourdomain.com # 실제 도메인으로 변경
    images-path: /images/

# 로그 설정
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.jdbc.core.JdbcTemplate: WARN
    org.springframework.jdbc.core.StatementCreatorUtils: ERROR
