spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pictz?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true # 테이블 생성 후 data.sql 실행하도록 설정
  sql:
    init:
      mode: never  # 애플리케이션 시작할때마다 data.sql 실행
      data-locations: classpath:db/data.sql # data.sql 경로 지정